In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
df = pd.read_csv("../data/my_file (1).csv")

In [62]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [63]:
df.tail()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [64]:
df.shape

(20, 11)

In [65]:
df.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [66]:
df.dtypes

Rank                                int64
Peak                                  str
All Time Peak                         str
Actual gross                          str
Adjusted gross (in 2022 dollars)      str
Artist                                str
Tour title                            str
Year(s)                               str
Shows                               int64
Average gross                         str
Ref.                                  str
dtype: object

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      str
 2   All Time Peak                     6 non-null      str
 3   Actual gross                      20 non-null     str
 4   Adjusted gross (in 2022 dollars)  20 non-null     str
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Year(s)                           20 non-null     str
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     str
 10  Ref.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 1.8 KB

In [68]:
df.describe()

            Rank       Shows
count  20.000000   20.000000
mean   10.450000  110.000000
std     5.942488   66.507617
min     1.000000   41.000000
25%     5.750000   59.000000
50%    10.500000   87.000000
75%    15.250000  134.500000
max    20.000000  325.000000

In [69]:
Numeric = df.select_dtypes(include="number")
Numeric

    Rank  Shows
0      1     56
1      2     56
2      3     85
3      4    156
4      5     53
5      6     88
6      7    131
7      7     41
8      9     49
9     10     85
10    11    132
11    12    203
12    13    151
13    14    325
14    15     60
15    16    142
16    17     98
17    18     82
18    19    121
19    20     86

In [70]:
Categorical = df.select_dtypes(include="object")
Categorical

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_23500\3616488947.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Categorical = df.select_dtypes(include="object")

,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Average gross,Ref.
0,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,"$13,928,571",[1]
1,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,"$10,353,571",[3]
2,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,"$4,835,294",[6]
3,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,"$2,546,795",[7]
4,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,"$6,522,173",[8]
5,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,"$3,467,709",[9]
6,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,"$2,137,405",[11]
7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,"$6,282,927",[12]
8,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,"$5,226,215",[13]
9,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,"$2,945,882",[14]
10,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,"$1,735,606",[15][16]
11,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,"$1,118,227",[18]
12,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,"$1,350,993",[19]
13,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,"$615,385",[20]
14,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,"$3,233,333",[5]
15,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,"$1,295,775",[22]
16,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,"$1,734,694",[d]
17,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,"$2,070,732",[4]
18,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,"$1,385,950",[25]
19,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,"$1,744,186",[26]

In [71]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [72]:
df.nunique()

Rank                                19
Peak                                 7
All Time Peak                        6
Actual gross                        20
Adjusted gross (in 2022 dollars)    20
Artist                               9
Tour title                          20
Year(s)                             16
Shows                               18
Average gross                       20
Ref.                                20
dtype: int64

In [73]:
Numeric

    Rank  Shows
0      1     56
1      2     56
2      3     85
3      4    156
4      5     53
5      6     88
6      7    131
7      7     41
8      9     49
9     10     85
10    11    132
11    12    203
12    13    151
13    14    325
14    15     60
15    16    142
16    17     98
17    18     82
18    19    121
19    20     86

In [74]:
df.columns.tolist()

['Rank',
 'Peak',
 'All Time Peak',
 'Actual\xa0gross',
 'Adjusted\xa0gross (in 2022 dollars)',
 'Artist',
 'Tour title',
 'Year(s)',
 'Shows',
 'Average gross',
 'Ref.']

In [77]:

df_cleaned = df.dropna()

In [78]:
df_cleaned.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [79]:
df_cleaned = df.drop_duplicates()

In [83]:
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      str
 2   All Time Peak                     6 non-null      str
 3   Actual gross                      20 non-null     str
 4   Adjusted gross (in 2022 dollars)  20 non-null     str
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Year(s)                           20 non-null     str
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     str
 10  Ref.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 1.8 KB

In [84]:
df_cleaned

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [ ]:
# Find Outliers in the numeric 
Q1 = Numeric.quantile(0.25)
Q3 = Numeric.quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [ ]:
# diff b/w nunique and unique
# nunique() returns the number of unique values in a column, while unique() returns an array of the unique values themselves.